# Generated by Django 2.1.7 on 2019-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_payment', '0002_order_is_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
