# Generated by Django 2.2.4 on 2019-09-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('froide_payment', '0006_auto_20190527_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('provider', models.CharField(blank=True, max_length=256)),
                ('remote_reference', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='provider',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_payment.Product'),
        ),
    ]
