# Generated by Django 2.2.4 on 2020-01-21 15:24

import django.utils.timezone
from django.db import migrations, models

import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("froide_payment", "0010_auto_20191216_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="received_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="customer",
            name="custom_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
