# Generated by Django 2.2.4 on 2020-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_payment", "0011_auto_20200121_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="canceled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
