# Generated by Django 3.0.5 on 2020-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_payment", "0013_auto_20200528_1201"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="customer",
            name="provider",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
