# Generated by Django 3.2.14 on 2022-09-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_payment", "0014_auto_20200610_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for input"),
                    ("preauth", "Pre-authorized"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("refunded", "Refunded"),
                    ("error", "Error"),
                    ("input", "Input"),
                    ("pending", "Confirmation pending"),
                    ("deferred", "Capture deferred"),
                    ("canceled", "Canceled"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
    ]
