# Generated by Django 4.1.4 on 2022-12-19 21:15

from django.db import migrations

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("froide_payment", "0015_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="billing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
