# Generated by Django 4.1.4 on 2023-01-20 13:28

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_payment", "0016_payment_billing_phone"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                models.F("remote_reference"),
                django.db.models.functions.datetime.Trunc("service_start", "day"),
                condition=models.Q(
                    models.Q(("remote_reference", ""), _negated=True),
                    ("service_start__isnull", False),
                ),
                name="unique_remote_reference_service_start",
            ),
        ),
    ]
