# Generated by Django 4.1.4 on 2023-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_payment", "0017_order_unique_remote_reference_service_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="slug",
            field=models.SlugField(max_length=256),
        ),
    ]
